Document: postgresql-9.4-jsonb-extend
Title: Debian postgresql-9.4-jsonb-extend Manual
Author: <insert document author here>
Abstract: This manual describes what postgresql-9.4-jsonb-extend is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/postgresql-9.4-jsonb-extend/postgresql-9.4-jsonb-extend.sgml.gz

Format: postscript
Files: /usr/share/doc/postgresql-9.4-jsonb-extend/postgresql-9.4-jsonb-extend.ps.gz

Format: text
Files: /usr/share/doc/postgresql-9.4-jsonb-extend/postgresql-9.4-jsonb-extend.text.gz

Format: HTML
Index: /usr/share/doc/postgresql-9.4-jsonb-extend/html/index.html
Files: /usr/share/doc/postgresql-9.4-jsonb-extend/html/*.html
