CREATE EXTENSION jsonb_extend;
select jsonb_extend('1'::jsonb, '[]'::jsonb);
select jsonb_extend('{"1": 2}'::jsonb, '[]'::jsonb);
select jsonb_extend('{}'::jsonb, '{}'::jsonb);
select jsonb_extend('[]'::jsonb, '[]'::jsonb);
select jsonb_extend('[]'::jsonb, '{}'::jsonb);
select jsonb_extend('[]'::jsonb, '1'::jsonb);
select jsonb_extend('[]'::jsonb, '"string"'::jsonb);
select jsonb_extend('{"a": 1}'::jsonb, '{"b": 2}'::jsonb);
select jsonb_extend('[1]'::jsonb, '[2]'::jsonb);
select jsonb_extend('[1]'::jsonb, '2'::jsonb);
select jsonb_extend('[1]'::jsonb, '{"a": 2}'::jsonb);
select jsonb_extend('{"a": 1}'::jsonb, '{"b": 2}'::jsonb);
select jsonb_extend('{"a": 1}'::jsonb, '{"b": 2, "a": 3}'::jsonb);
select jsonb_extend('{"a": 1, "b": 3}'::jsonb, '{"b": 2}'::jsonb);
select jsonb_extend('{"a": 1, "b": 2}'::jsonb, '{"b": {"c": 3}}'::jsonb);
select jsonb_extend('{"a": 1, "b": {"c": 3}}'::jsonb, '{"b": {"d": 4}}'::jsonb);
select jsonb_deep_extend('{}'::jsonb, '{}'::jsonb, false);
select jsonb_deep_extend('{"a": 1}'::jsonb, '{}'::jsonb, false);
select jsonb_deep_extend('{}'::jsonb, '{"a": 1}'::jsonb, false);
select jsonb_deep_extend('{"b": 2}'::jsonb, '{"a": 1}'::jsonb, false);
select jsonb_deep_extend('{"b": 2, "a": 1}'::jsonb, '{"a": [1]}'::jsonb, false);
select jsonb_deep_extend('{"b": [{"c": 2}], "a": 1}'::jsonb, '{"a": [{"c": 1}]}'::jsonb, false);
select jsonb_deep_extend('{"b": {"c": 2}}'::jsonb, '{"a": 1}'::jsonb, false);
select jsonb_deep_extend('{"b": {"c": 2}}'::jsonb, '{"b": {"a": 1}}'::jsonb, false);
select jsonb_deep_extend('{"a": 1, "b": {"c": 3}}'::jsonb, '{"b": {"d": 4}}'::jsonb, false);
select jsonb_deep_extend('{"a": {"b": 1, "c": 2}}'::jsonb, '{"a": 23}'::jsonb, false);
